export const T = {
  bg:           "#f7f8f6",
  surface:      "#ffffff",
  surfaceAlt:   "#f4f5f3",
  overlay:      "#1a1a1a",
  brand:        "#2e9e7a",
  brandLight:   "#e8f7f2",
  brandBorder:  "#b8e8d8",
  text:         "#1a1c1a",
  textSub:      "#5a6060",
  textHint:     "#9aacac",
  border:       "#e2e6e2",
  borderHover:  "#c4cec4",
  teal:         "#2e9e7a",  tealLight:  "#e8f7f2",  tealBorder:  "#b8e8d8",
  orange:       "#e07b2e",  orangeLight:"#fef3e8",  orangeBorder:"#f5d0a9",
  pink:         "#c45a7a",  pinkLight:  "#fdeef3",  pinkBorder:  "#f0b8cc",
  blue:         "#4a7cc9",  blueLight:  "#edf3fc",  blueBorder:  "#bed1f0",
  red:          "#d04040",  redLight:   "#fdeaea",  redBorder:   "#f0b0b0",
  green:        "#2e8a5a",  greenLight: "#eaf5ee",  greenBorder: "#b0ddc0",
  amber:        "#c88a20",  amberLight: "#fdf6e8",  amberBorder: "#f0d898",
  codeBg:       "#f9faf8",
  codeText:     "#2c3030",
  codeNum:      "#c0caca",
  codeHl:       "#e8f7f2",
  kwColor:      "#7c4dcc",
  strColor:     "#2e7a40",
  fnColor:      "#4a7cc9",
  cmColor:      "#9aacac",
  r:            "6px",
  rMd:          "8px",
  rLg:          "12px",
}
